### ISSUE TITLE
Cannot run compiler, getting error `Built-in class kotlin.Any is not found`

### ISSUE THREAD

**Issue by LewsTherinTelescope** [dotlin-org/dotlin#5]
Trying to run the `dotlin` command gives me the following error:

```
Exception in thread "main" java.lang.AssertionError: Built-in class kotlin.Any is not found
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:93)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:88)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getBuiltInClassByName(KotlinBuiltIns.java:223)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getAny(KotlinBuiltIns.java:228)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getAnyType(KotlinBuiltIns.java:498)
        at org.jetbrains.kotlin.psi2ir.descriptors.IrBuiltInsOverDescriptors.<init>(IrBuiltInsOverDescriptors.kt:242)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.createGeneratorContext(Psi2IrTranslator.kt:70)
        at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.createGeneratorContext$default(Psi2IrTranslator.kt:54)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.loadIr(SourceToIr.kt:157)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.sourceToIr(SourceToIr.kt:71)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:98)
        at org.dotlin.compiler.KotlinToDartCompiler.compile$default(KotlinToDartCompiler.kt:88)
        at org.dotlin.compiler.cli.command.Compile.run(Compile.kt:48)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.dotlin.compiler.Dotlin.main(Main.kt:26)
```

A few notes:
- All automated tests pass just fine and generate the correct Dart files.
- I've verified that the Dotlin classpath is indeed set to include the stdlib, and even tried compiling and running the compiler as a fat JAR, but no dice.
- The same exception occurs when running the `main` function directly from the IDE.
- Help message displays fine, the issue only happens when trying to run the compiler.
- Content of the current directory doesn't seem to matter, it happens whether there's zero files or many. 

Device info:
- OS: macOS Ventura 13.0.1
- Java: Both OpenJDK 17 & 19
- Dotlin: 03493a1 (`main` branch at time of writing)

**Comment by wilkomanger** [comment]
Thanks for the detailed report!

So with the current CLI you have to pass the stdlib as a dependency using `--dependency`. In this case, `--dependency $DOTLIN_REPO/libraries/stdlib`. Should work then!

I'm currently in the process of letting Dotlin use the Dart project structure, meaning dependencies will be specified using `pubspec.yaml` (`--dependency` will be gone). So if it doesn't work, you can wait for that :+1:

**Comment by wilkomanger** [comment]
Yes, you're right. Sorry, my mind is already set in the new way :sweat_smile: Which is indeed what I'm working on currently.

I've had a look, and if you checkout 6c894a401eb1f5d146f71e84839743b9b94f71aa, specifying the `--dependency` will work. It must however be a .klib file, so you'll have to compile the stdlib first. Running the [`StandardLibrary`](https://github.com/dotlin-org/dotlin/blob/6c894a401eb1f5d146f71e84839743b9b94f71aa/compiler/src/test/kotlin/compile/klib/StandardLibrary.kt) test is the easiest way to that. You might still encounter errors since that way of specifying dependencies was only temporary, but for simple things it should work :+1:

**Comment by wilkomanger** [comment]
Awesome, thank you :+1:

**Comment by eggnstone** [comment]
I understand the project is under heavy development but could you point us to a usable version/commit?
Or just some very basic instructions?
I still get the "Built-in class kotlin.Any is not found"

**Comment by wilkomanger** [comment]
The upcoming 0.1.0 will be the first real usable version, with a proper CLI!

But I've just it fixed a tad so you can at least try it out, and you won't need the steps mentioned above anymore. Here are the steps:

1. Checkout at 0472fb138603996ee70df2c7dcb5ee6e243328c3
2. Run `./gradlew build distZip -x test` in `compiler/`
3. Run `cd build/distributions && unzip dotlin-0.0.1.zip`
4. Either add `$DOTLIN_PATH/compiler/build/distributions/dotlin-0.0.1/bin` to your `PATH` or just run it directly in the next steps (with `$DOTLIN_PATH` being the path you cloned the repo to)
5. Create a project directory somewhere with the following `pubspec.yaml` in it (replace `$DOTLIN_PATH` with the cloned repo path):
    ```yaml
    name: test
    version: 1.0.0

    environment:
      sdk: '>=2.18.0 <3.0.0'

    publish_to: none

    dependencies:
      dotlin:
        path: $DOTLIN_PATH/packages/dotlin
    
    dev_dependencies:
      dotlin_generator:
        path: $DOTLIN_PATH/packages/dotlin_generator
    ``` 
6. Write a Kotlin file to `lib/Test.kt` and put something in there
7. Run `dotlin` (or `$DOTLIN_PATH//compiler/build/distributions/dotlin-0.0.1/bin/dotlin`) in your created project path root
8. You'll see a generated `lib/test.dt.g.dart` file :+1: 

Let me know if it works :smile:

**Comment by eggnstone** [comment]
Thank you for your swift response and fix!
Looking forward to your release!

I followed your instructions and when executing dotlin I got this error:
(Running under Windows10 with git bash (mingw64) and Java19)
```
Exception in thread "main" java.lang.IllegalArgumentException: Missing scheme
        at java.base/java.nio.file.Path.of(Path.java:199)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at org.dotlin.compiler.backend.DartProject$Companion.from(DartPackage.kt:106)
        at org.dotlin.compiler.backend.DartProject$Companion$from$1.invokeSuspend(DartPackage.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:79)
        at org.dotlin.compiler.cli.command.Compile.run(Compile.kt:37)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.dotlin.compiler.Dotlin.main(Main.kt:26)

```

Test.kt:
```
class Test
{
    companion object
    {
        fun x() = "Hello"
    }
}
```
pubspec.yaml:
```
name: test
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

publish_to: none

dependencies:
  dotlin:
    path: ../../../GitHub/dotlin/packages/dotlin

dev_dependencies:
  dotlin_generator:
    path: ../../../GitHub/dotlin/packages/dotlin_generator

```

**Comment by eggnstone** [comment]
I fixed the scheme problem by using an absolute path instead of a relative one.

But then I get this error:
```
Exception in thread "main" java.lang.AssertionError: Built-in class kotlin.Any is not found
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:93)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:88)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getBuiltInClassByName(KotlinBuiltIns.java:223)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getAny(KotlinBuiltIns.java:228)
        at org.jetbrains.kotlin.builtins.KotlinBuiltIns.getAnyType(KotlinBuiltIns.java:498)
        at org.jetbrains.kotlin.resolve.DescriptorResolver.getDefaultSupertype(DescriptorResolver.java:199)
        at org.jetbrains.kotlin.resolve.DescriptorResolver.resolveSupertypes(DescriptorResolver.java:169)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.computeSupertypes(LazyClassDescriptor.java:867)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$LazyClassTypeConstructor.computeSupertypes(LazyClassDescriptor.java:764)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:78)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:77)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValueWithPostCompute.invoke(LockBasedStorageManager.java:481)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValueWithPostCompute.invoke(LockBasedStorageManager.java:512)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:27)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:26)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getSuperClassNotAny(DescriptorUtils.kt:145)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAllSuperclassesWithoutAny(DescriptorUtils.kt:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:50)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:49)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForCompanionObjectHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:61)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForCompanionObjectHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:60)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForCompanionObjectHeaderResolution(LazyClassDescriptor.java:425)
        at org.jetbrains.kotlin.resolve.lazy.DeclarationScopeProviderImpl.getResolutionScopeForDeclaration(DeclarationScopeProviderImpl.java:72)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getOuterScope(LazyClassDescriptor.java:407)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:42)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForClassHeaderResolution$1.invoke(ClassResolutionScopesSupport.kt:41)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForClassHeaderResolution(LazyClassDescriptor.java:413)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.computeSupertypes(LazyClassDescriptor.java:867)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor$LazyClassTypeConstructor.computeSupertypes(LazyClassDescriptor.java:764)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:78)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor$supertypes$1.invoke(AbstractTypeConstructor.kt:77)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValueWithPostCompute.invoke(LockBasedStorageManager.java:481)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValueWithPostCompute.invoke(LockBasedStorageManager.java:512)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:27)
        at org.jetbrains.kotlin.types.AbstractTypeConstructor.getSupertypes(AbstractTypeConstructor.kt:26)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getSuperClassNotAny(DescriptorUtils.kt:145)
        at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getAllSuperclassesWithoutAny(DescriptorUtils.kt:364)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:50)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithoutMe$1.invoke(ClassResolutionScopesSupport.kt:49)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:56)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$inheritanceScopeWithMe$1.invoke(ClassResolutionScopesSupport.kt:55)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:65)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.ClassResolutionScopesSupport$scopeForMemberDeclarationResolution$1.invoke(ClassResolutionScopesSupport.kt:64)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:408)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:527)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassDescriptor.getScopeForMemberDeclarationResolution(LazyClassDescriptor.java:431)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getScopeForMemberDeclarationResolution(LazyClassMemberScope.kt:209)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getDeclaredFunctions(AbstractLazyMemberScope.kt:122)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$getDeclaredFunctions(AbstractLazyMemberScope.kt:38)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$declaredFunctionDescriptors$1.invoke(AbstractLazyMemberScope.kt:58)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$declaredFunctionDescriptors$1.invoke(AbstractLazyMemberScope.kt:58)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.doGetFunctions(AbstractLazyMemberScope.kt:101)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.access$doGetFunctions(AbstractLazyMemberScope.kt:38)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:51)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope$functionDescriptors$1.invoke(AbstractLazyMemberScope.kt:51)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
        at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:651)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.AbstractLazyMemberScope.getContributedFunctions(AbstractLazyMemberScope.kt:97)
        at org.jetbrains.kotlin.resolve.lazy.descriptors.LazyClassMemberScope.getContributedFunctions(LazyClassMemberScope.kt:280)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitNamedFunction(LazyDeclarationResolver.kt:125)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver$resolveToDescriptor$1.visitNamedFunction(LazyDeclarationResolver.kt:94)
        at org.jetbrains.kotlin.psi.KtNamedFunction.accept(KtNamedFunction.java:51)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:94)
        at org.jetbrains.kotlin.resolve.lazy.LazyDeclarationResolver.resolveToDescriptor(LazyDeclarationResolver.kt:91)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.createFunctionDescriptors(LazyTopDownAnalyzer.kt:284)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:206)
        at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations$default(LazyTopDownAnalyzer.kt:58)
        at org.dotlin.compiler.backend.steps.src2ir.analyze.DotlinAnalyzer.analyze(DotlinAnalyzer.kt:132)
        at org.dotlin.compiler.backend.steps.src2ir.analyze.DartKotlinAnalyzerReporter$analyzeAndReport$report$1$1.invoke(DotlinAnalyzerReporter.kt:58)
        at org.dotlin.compiler.backend.steps.src2ir.analyze.DartKotlinAnalyzerReporter$analyzeAndReport$report$1$1.invoke(DotlinAnalyzerReporter.kt:57)
        at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
        at org.dotlin.compiler.backend.steps.src2ir.analyze.DartKotlinAnalyzerReporter.analyzeAndReport(DotlinAnalyzerReporter.kt:57)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.loadIr(SourceToIr.kt:105)
        at org.dotlin.compiler.backend.steps.src2ir.SourceToIrKt.sourceToIr(SourceToIr.kt:59)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:93)
        at org.dotlin.compiler.KotlinToDartCompiler.compile$default(KotlinToDartCompiler.kt:83)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:78)
        at org.dotlin.compiler.cli.command.Compile.run(Compile.kt:37)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.dotlin.compiler.Dotlin.main(Main.kt:26)
```

**Comment by eggnstone** [comment]
Using Open-JDK 17.0.2: same result

**Comment by wilkomanger** [comment]
Sorry, forget a step! You should run the compiler also in `$DOTLIN_PATH/packages/dotlin`, to build the stdlib. Then compiling your project should work :+1:

**Comment by eggnstone** [comment]
Works now!
Thanks a bunch!
