### ISSUE TITLE
[Windows?] Since 113dcb4: When compiling stdlib: Cannot run program "dart" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by eggnstone** [dotlin-org/dotlin#92]
```
Exception in thread "main" java.io.IOException: Cannot run program "dart" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt$runCommand$2.invokeSuspend(ProcessUtils.kt:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 10 more

```

**Comment by wilkomanger** [comment]
To confirm, you don't have this issue at 1e799ed0b8f8f641ae4ec3c03b80272c39d37a33?

**Comment by eggnstone** [comment]
> To confirm, you don't have this issue at [1e799ed](https://github.com/dotlin-org/dotlin/commit/1e799ed0b8f8f641ae4ec3c03b80272c39d37a33)?

Correct

**Comment by eggnstone** [comment]
> To confirm, you don't have this issue at [1e799ed](https://github.com/dotlin-org/dotlin/commit/1e799ed0b8f8f641ae4ec3c03b80272c39d37a33)?

I still have it with 1e799ed. That's why I mentioned "since". Also tried 634bf74.

**Comment by eggnstone** [comment]
Also occurs with e5e7c00.

**Comment by wilkomanger** [comment]
I see, thanks :+1: If it's not too much trouble, do you know at which commit in the past you don't have the issue?

**Comment by eggnstone** [comment]
> I see, thanks 👍 If it's not too much trouble, do you know at which commit in the past you don't have the issue?

That's why I wrote "since". The commit before was fine.
Maybe I should be more explicit with what I write :)

**Comment by wilkomanger** [comment]
Ah sorry :sweat_smile: I thought you still had the error at 1e799ed0b8f8f641ae4ec3c03b80272c39d37a33. I understand now, thanks :+1:

**Comment by wilkomanger** [comment]
Do you still get the issue if you run `dart pub get` in the project root before running the compiler?

**Comment by eggnstone** [comment]
Yes, the error is still there.

I can run dart from the command line and "dart pub get" in packages/dotlin worked but then compiling the stdlib did produce the same error as before:

```
Exception in thread "main" java.io.IOException: Cannot run program "dart" (in directory "......\GitHub\dotlin\packages\dotlin"): CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt$runCommand$2.invokeSuspend(ProcessUtils.kt:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 10 more

```

**Comment by wilkomanger** [comment]
I've installed a Windows VM and fixed multiple Windows-only issues, including this one :smile: At a5647958f8586495b3c763d75bd4d2d01d2804ab you should be able to compile the stdlib and your projects normally :+1: You might have to run `dart pub cache repair` if you get an error about an illegal token `:` in a path.

Let me know if it works for you :+1:

**Comment by eggnstone** [comment]
Awesome!

However, I get the following error (despite running dart pub cache repair)

```
Compiling stdlib
Exception in thread "main" java.util.regex.PatternSyntaxException: Unexpected internal error near index 3
^~\
        at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1789)
        at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
        at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
        at kotlin.text.Regex.<init>(Regex.kt:89)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt.findBinary(ProcessUtils.kt:42)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt.access$findBinary(ProcessUtils.kt:1)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt$runCommand$2.invokeSuspend(ProcessUtils.kt:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by wilkomanger** [comment]
Can you try with e70a100ce82c2e212033aceb9ba4a6075b36c79b?

**Comment by eggnstone** [comment]
Ouch:

Compiling stdlib
Exception in thread "main" java.io.IOException: Cannot run program "C:\......\Flutter\bin\dart.bat" (in directory ""): CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.dotlin.compiler.backend.util.ProcessUtilsKt$runCommand$2.invokeSuspend(ProcessUtils.kt:20)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: CreateProcess error=123, The filename, directory name, or volume label syntax is incorrect
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 10 more

**Comment by eggnstone** [comment]
I'm using git bash by the way

**Comment by wilkomanger** [comment]
I see :thinking: Did you add the dots in `C:......\Flutter\bin\dart.bat` or was it printed exactly like that?

**Comment by eggnstone** [comment]
And the path is correct, by the way, and does work in the shell, if I escape the escapes \\

**Comment by wilkomanger** [comment]
Cool, yeah that's all I need to know :+1:

**Comment by wilkomanger** [comment]
Can't seem to reproduce it :thinking: The path does point to an existing file?

**Comment by wilkomanger** [comment]
Interesting :thinking: I'll close this, but feel free to reopen if it happens again :+1:

**Comment by eggnstone** [comment]
This reoccurs when dart needs to run.
I disabled the directory-line and then it works:
```
        val process = ProcessBuilder(*resolvedCommand)
            //.directory(workingDirectory?.toFile())
            .start()
```

**Comment by wilkomanger** [comment]
Interesting! And the `(in directory "")` part of the exception was literally like that?

**Comment by eggnstone** [comment]
> Interesting! And the `(in directory "")` part of the exception was literally like that?

yes

**Comment by wilkomanger** [comment]
Can you try again at 27b758d2073484dc36f096b064af4c1fb33bb0d2?

**Comment by eggnstone** [comment]
Fixed! 👍
