### ISSUE TITLE
Transformer error occurred: class IrTryImpl cannot be cast to class IrVariable

### ISSUE THREAD

**Issue by wilkomanger** [dotlin-org/dotlin#96]
```
Exception in thread "main" org.dotlin.compiler.backend.DotlinTransformerError: Transformer error occurred: class org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl cannot be cast to class org.jetbrains.kotlin.ir.declarations.IrVariable (org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl and org.jetbrains.kotlin.ir.declarations.IrVariable are in unnamed module of loader 'app')

While processing:
BLOCK type=kotlin.Unit origin=FOR_LOOP

        at org.dotlin.compiler.backend.ErrorsKt$runAndReportTransformerError$1.invoke(Errors.kt:96)
        at org.dotlin.compiler.backend.ErrorsKt$runAndReportTransformerError$1.invoke(Errors.kt:96)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:89)

```

_Originally posted by @eggnstone in https://github.com/dotlin-org/dotlin/issues/38#issuecomment-1464952713_

**Comment by wilkomanger** [comment]
Is that the full stack trace or is there more?

**Comment by eggnstone** [comment]
```
Exception in thread "main" org.dotlin.compiler.backend.DotlinTransformerError: Transformer error occurred: class org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl cannot be cast to class org.jetbrains.kotlin.ir.declarations.IrVariable (org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl and org.jetbrains.kotlin.ir.declarations.IrVariable are in unnamed module of loader 'app')

While processing:
BLOCK type=kotlin.Unit origin=FOR_LOOP

        at org.dotlin.compiler.backend.ErrorsKt$runAndReportTransformerError$1.invoke(Errors.kt:96)
        at org.dotlin.compiler.backend.ErrorsKt$runAndReportTransformerError$1.invoke(Errors.kt:96)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:89)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReportTransformerError(Errors.kt:96)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitBlock(IrDartAstTransformer.kt:48)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitBlock(IrDartAstTransformer.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:22)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementKt.accept(IrToDartStatement.kt:363)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementKt.accept(IrToDartStatement.kt:364)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartFunctionBodyTransformer.visitBlockBody(IrToDartFunctionBody.kt:45)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartFunctionBodyTransformer.visitBlockBody(IrToDartFunctionBody.kt:33)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitBlockBody$1$1.invoke(IrDartAstTransformer.kt:54)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitBlockBody$1$1.invoke(IrDartAstTransformer.kt:54)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:86)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReportTransformerError(Errors.kt:96)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitBlockBody(IrDartAstTransformer.kt:54)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitBlockBody(IrDartAstTransformer.kt:31)
        at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:24)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartFunctionBodyKt.accept(IrToDartFunctionBody.kt:62)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartFunctionBodyKt.accept$default(IrToDartFunctionBody.kt:59)
        at org.dotlin.compiler.backend.steps.ir2ast.DartAstTransformContext.transformBy(DartAstTransformContext.kt:70)
        at org.dotlin.compiler.backend.steps.ir2ast.DartAstTransformContext.transformBy(DartAstTransformContext.kt:93)
        at org.dotlin.compiler.backend.steps.ir2ast.DartAstTransformContext.transformBy$default(DartAstTransformContext.kt:89)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartClassMemberTransformer.visitSimpleFunction(IrToDartClassMember.kt:49)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartClassMemberTransformer.visitSimpleFunction(IrToDartClassMember.kt:46)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitSimpleFunction$1$1.invoke(IrDartAstTransformer.kt:454)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitSimpleFunction$1$1.invoke(IrDartAstTransformer.kt:454)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:86)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReportTransformerError(Errors.kt:96)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitSimpleFunction(IrDartAstTransformer.kt:454)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitSimpleFunction(IrDartAstTransformer.kt:31)
        at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:36)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartClassMemberKt.acceptAsClassMember(IrToDartClassMember.kt:192)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartDeclarationTransformer$visitClass$members$3.invoke(IrToDartDeclaration.kt:147)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartDeclarationTransformer$visitClass$members$3.invoke(IrToDartDeclaration.kt:147)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartDeclarationTransformer.visitClass(IrToDartDeclaration.kt:148)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartDeclarationTransformer.visitClass(IrToDartDeclaration.kt:42)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitClass$1$1.invoke(IrDartAstTransformer.kt:98)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitClass$1$1.invoke(IrDartAstTransformer.kt:98)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:86)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReportTransformerError(Errors.kt:96)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitClass(IrDartAstTransformer.kt:98)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitClass(IrDartAstTransformer.kt:31)
        at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:64)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartDeclarationKt.accept(IrToDartDeclaration.kt:224)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartCompilationUnitTransformer.visitFile(IrToDartCompilationUnit.kt:36)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartCompilationUnitTransformer.visitFile(IrToDartCompilationUnit.kt:32)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitFile$1$1.invoke(IrDartAstTransformer.kt:283)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitFile$1$1.invoke(IrDartAstTransformer.kt:283)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:86)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReportTransformerError(Errors.kt:96)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitFile(IrDartAstTransformer.kt:283)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer.visitFile(IrDartAstTransformer.kt:31)
        at org.jetbrains.kotlin.ir.declarations.IrFile.accept(IrFile.kt:30)
        at org.dotlin.compiler.backend.steps.ir2ast.IrToDartAstKt.irToDartAst(IrToDartAst.kt:58)
        at org.dotlin.compiler.KotlinToDartCompiler.generateDartCode(KotlinToDartCompiler.kt:147)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:77)
        at org.dotlin.compiler.KotlinToDartCompiler.compile$default(KotlinToDartCompiler.kt:57)
        at org.dotlin.compiler.KotlinToDartCompiler.compile(KotlinToDartCompiler.kt:52)
        at org.dotlin.compiler.cli.command.Compile.run(Compile.kt:37)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.dotlin.compiler.Dotlin.main(Main.kt:26)
Caused by: java.lang.ClassCastException: class org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl cannot be cast to class org.jetbrains.kotlin.ir.declarations.IrVariable (org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl and org.jetbrains.kotlin.ir.declarations.IrVariable are in unnamed module of loader 'app')
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementTransformer$visitBlock$loopVariables$2.invoke(IrToDartStatement.kt:174)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementTransformer$visitBlock$loopVariables$2.invoke(IrToDartStatement.kt:173)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementTransformer.visitBlock$lambda$7(IrToDartStatement.kt:173)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementTransformer.visitBlock(IrToDartStatement.kt:264)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrToDartStatementTransformer.visitBlock(IrToDartStatement.kt:55)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitBlock$1$1.invoke(IrDartAstTransformer.kt:48)
        at org.dotlin.compiler.backend.steps.ir2ast.transformer.IrDartAstTransformer$visitBlock$1$1.invoke(IrDartAstTransformer.kt:48)
        at org.dotlin.compiler.backend.ErrorsKt.runAndReport(Errors.kt:86)
        ... 68 more

```

**Comment by wilkomanger** [comment]
I'm trying to reproduce it with your project (DartFormatJetbrainsPlugin) on a Windows VM, but I don't see a `pubspec.yaml` anywhere. Can you tell me the steps on how you're currently your project so I can reproduce?

**Comment by eggnstone** [comment]
`DartFormatJetbrainsPlugin` is a JetBrains plugin and Kotlin-only.
`dart_format` is a pub_dev package which pulls in the sources from `DartFormatJetbrainsPlugin` and uses dotlin to transpile them.
You need both repos.
Then call `dotlin.sh` in `dart_format`
(I want to publish the DartFormatter I am writing for JetBrains also as a package to be used in a pipeline using dart, that's why I came up with using dotlin in the first place.)

**Comment by eggnstone** [comment]
https://github.com/eggnstone/dart_format

**Comment by wilkomanger** [comment]
Ah interesting, thanks! Will have a look :+1:

**Comment by wilkomanger** [comment]
I can reproduce it :+1:

**Comment by wilkomanger** [comment]
I've fixed all issues I encountered while compiling your project (meaning this and #98). You should be able to compile now without errors! Let me know if it works for you :+1:

**Comment by eggnstone** [comment]
Awesome! Works! 👍 

(but other bugs coming :)

**Comment by wilkomanger** [comment]
Hehe, no problem, keep 'm coming :+1:
